export const AI_SETTINGS = {
  screenTitle: 'AI戦略アシスタント設定',
  screenSubtitle: 'OpenAI互換API · 個人利用の分析補助',
  apiKeyLabel: 'AI APIキー',
  apiKeyHint:
    'OpenAIなどのAPIキーを入力します。キーは端末のSecureStoreにのみ保存され、会話本文には含めません。',
  apiKeyPlaceholder: 'YOUR_API_KEY_HERE',
  saveKey: 'APIキーを保存',
  savedKey: 'AI APIキーを保存しました。',
  aiEnabledLabel: 'AI機能を有効にする',
  aiEnabledHint: 'オフの場合は常にモック応答を表示します。',
  mockOnlyLabel: 'モックAIのみ使用',
  mockOnlyHint: 'APIキーがあっても外部APIへ送信しません。',
  dataTitle: 'AIへ送信するデータ',
  dataBody:
    '送信されるのは正規化された要約のみです: 保有銘柄（銘柄・市場・株数・鮮度）、ウォッチリスト、リスクモード、マーケットレジーム、健全性チェック結果の概要、執行ジャーナルの件数・要約、直近のAI推奨カードの要約。\n\n送信しません: APIキー、認証情報、個人情報、生のジャーナル全文、ポートフォリオの生ダンプ、生APIレスポンス。',
  clearHistory: 'AI会話履歴をクリア',
  clearHistoryConfirm: 'ホームのAIチャット履歴を削除します。よろしいですか？',
  clearHistoryDone: '会話履歴をクリアしました。',
  personalLabel: '個人利用の分析補助',
  explanationLevelLabel: '説明レベル',
  explanationLevelHint: 'AIコンシェルジュの話し方・用語の難しさを選びます。AIの人格（冷静・分析的）は変わりません。',
  explanationLevelCurrent: '現在の選択',
  connectionStatusLabel: 'OpenAI接続状態',
  connectionTestButton: 'AI API接続テスト',
  connectionTesting: '接続確認中…',
  connectionTestSuccess: '実API接続成功',
  keySavedUnverified: 'APIキー保存済み・未確認',
  openDiagnostics: 'API接続診断を開く',
  voiceEnabledLabel: '音声読み上げ',
  voiceEnabledHint: 'AI回答をスピーカーで再生できます。',
  voiceAutoReadLabel: '自動読み上げ',
  voiceAutoReadHint: 'AI回答が届いたら自動で読み上げます。',
  voiceRateLabel: '読み上げ速度',
  voiceRateSlow: 'ゆっくり',
  voiceRateNormal: '標準',
  voiceRateFast: '速い',
  urgentAlertsTitle: '緊急シグナル通知',
  urgentAlertsHint: 'ヘッダーに表示される「緊急」シグナルのみ振動・音で通知します（デフォルトON）。',
  urgentVibrationLabel: '緊急シグナルのバイブ',
  urgentVibrationHint: '緊急のみ短い振動で通知します（デフォルトON）。',
  urgentSoundLabel: '緊急シグナルの音',
  urgentSoundHint: '緊急のみ短い音で通知します（デフォルトON）。',
} as const;
