/** @deprecated src/constants/investmentCharter.ts を正本として使用 */
export {
  AI_CONCIERGE_INVESTMENT_CHAIR_JA,
  CHARTER_MIN_APPROVAL_REASONS as MIN_COMMITTEE_REASONS_TOTAL,
  CHARTER_MIN_BUY_CONFIDENCE_PCT as MIN_BUY_CONFIDENCE_PCT,
  CHARTER_MIN_BUY_SCORE as MIN_BUY_RECOMMENDATION_SCORE,
  COMMITTEE_DECISION_HIERARCHY_JA,
  OPPOSITION_FALLBACK_JA,
  USER_FINAL_APPROVAL_NOTE_JA,
} from './investmentCharter';
