export const RESUME_COORDINATOR_GLOBAL_GATE_MS = 12_000;
export const RESUME_COORDINATOR_HYDRATION_PAUSE_MS = 800;
export const RESUME_COORDINATOR_TELEMETRY_DEFER_MS = 2_000;
export const RESUME_COORDINATOR_ASYNC_DRAIN_MS = 1_500;
export const RESUME_COORDINATOR_WS_RESTORE_DELAY_MS = 2_500;
export const RESUME_BURST_BUDGET_PER_TICK = 1;
export const RESUME_RECONNECT_COALESCE_WINDOW_MS = 3_000;
