export const STORAGE_KEYS = {
  appState: '@sta/app_state',
  twelveDataApiKey: '@sta/twelve_data_api_key',
  newsApiKey: '@sta/news_api_key',
  snsApiKey: '@sta/sns_api_key',
  earningsApiKey: '@sta/earnings_api_key',
  aiLearning: '@sta/ai_learning',
  bursaSymbolFormat: '@sta/bursa_symbol_format_v1',
  marketDataDiagnostics: '@sta/market_data_diagnostics_v1',
  ohlcvCache: '@sta/ohlcv_cache_v1',
  governanceState: '@sta/governance_state_v1',
  governanceAuditLog: '@sta/governance_audit_v1',
  shadowPortfolio: '@sta/shadow_portfolio_v1',
  adaptiveLearning: '@sta/adaptive_learning_v1',
  marketIntelligenceSnapshot: '@sta/market_intelligence_v1',
  operatorBehavior: '@sta/operator_behavior_v1',
  modelStability: '@sta/model_stability_v1',
  metaCapital: '@sta/meta_capital_v1',
  quoteCache: '@sta/quote_cache_v1',
  portfolioBackup: '@sta/portfolio_backup_v1',
  portfolioHealthySnapshot: '@sta/portfolio_healthy_snapshot_v2',
  executionJournal: '@sta/execution_journal_v1',
  aiPreferences: '@sta/ai_preferences_v1',
  aiChatHistory: '@sta/ai_chat_history_v1',
  tradeQueueAck: '@sta/trade_queue_ack_v1',
  apiHealthSnapshot: '@sta/api_health_snapshot_v1',
} as const;
