export const STORAGE_KEYS = {
  appState: '@sta/app_state',
  twelveDataApiKey: '@sta/twelve_data_api_key',
  newsApiKey: '@sta/news_api_key',
  snsApiKey: '@sta/sns_api_key',
  earningsApiKey: '@sta/earnings_api_key',
  aiLearning: '@sta/ai_learning',
  bursaSymbolFormat: '@sta/bursa_symbol_format_v1',
  marketDataDiagnostics: '@sta/market_data_diagnostics_v1',
  ohlcvCache: '@sta/ohlcv_cache_v1',
  governanceState: '@sta/governance_state_v1',
  governanceAuditLog: '@sta/governance_audit_v1',
  shadowPortfolio: '@sta/shadow_portfolio_v1',
  adaptiveLearning: '@sta/adaptive_learning_v1',
  marketIntelligenceSnapshot: '@sta/market_intelligence_v1',
  operatorBehavior: '@sta/operator_behavior_v1',
  modelStability: '@sta/model_stability_v1',
  metaCapital: '@sta/meta_capital_v1',
  quoteCache: '@sta/quote_cache_v1',
  yahooSymbolAlias: '@sta/yahoo_symbol_alias_v1',
  portfolioBackup: '@sta/portfolio_backup_v1',
  portfolioHealthySnapshot: '@sta/portfolio_healthy_snapshot_v2',
  executionJournal: '@sta/execution_journal_v1',
  aiPreferences: '@sta/ai_preferences_v1',
  appUxMode: '@sta/app_ux_mode_v1',
  aiChatHistory: '@sta/ai_chat_history_v1',
  tradeQueueAck: '@sta/trade_queue_ack_v1',
  apiHealthSnapshot: '@sta/api_health_snapshot_v1',
  proactiveSuggestions: '@sta/proactive_suggestions_v1',
  xApiDailyUsage: '@sta/x_api_daily_usage_v1',
  xApiSymbolCache: '@sta/x_api_symbol_cache_v1',
  xApiOptionalMode: '@sta/x_api_optional_mode_v1',
  newsSymbolCache: '@sta/news_symbol_cache_v1',
  conciergePromptDebug: '@sta/concierge_prompt_debug_v1',
  portfolioIntelligence: '@sta/portfolio_intelligence_v1',
  autonomousMonitoring: '@sta/autonomous_monitoring_v1',
  metaDecision: '@sta/meta_decision_v1',
  strategyExecution: '@sta/strategy_execution_v1',
  portfolioReality: '@sta/portfolio_reality_v1',
  paperBroker: '@sta/paper_broker_v1',
  selfEvaluation: '@sta/self_evaluation_v1',
  macroIntelligence: '@sta/macro_intelligence_v1',
  dataReliability: '@sta/data_reliability_v1',
  portfolioRiskExposure: '@sta/portfolio_risk_exposure_v1',
  capitalAllocation: '@sta/capital_allocation_v1',
  systemStabilityIntegrity: '@sta/system_stability_integrity_v1',
  aiGovernanceDecision: '@sta/ai_governance_decision_v1',
  reactiveEventOrchestration: '@sta/reactive_event_orchestration_v1',
  explainableCognitiveTrace: '@sta/explainable_cognitive_trace_v1',
  adaptiveResourceComputeBudget: '@sta/adaptive_resource_compute_budget_v1',
  stateIntegrityTemporalConsistency: '@sta/state_integrity_temporal_consistency_v1',
  semanticConsistencyDecisionCoherence: '@sta/semantic_consistency_decision_coherence_v1',
  epistemicReliabilityEvidenceWeight: '@sta/epistemic_reliability_evidence_weight_v1',
  cognitiveGoalArbitrationIntentPriority: '@sta/cognitive_goal_arbitration_intent_priority_v1',
  metaCognitiveRiskReflectionSelfCritique: '@sta/meta_cognitive_risk_reflection_self_critique_v1',
  recursiveMemoryCompressionStrategicAbstraction:
    '@sta/recursive_memory_compression_strategic_abstraction_v1',
  systemicStabilityRecursiveGovernance: '@sta/systemic_stability_recursive_governance_v1',
  executionRecoveryAdaptiveConfidence: '@sta/execution_recovery_adaptive_confidence_v1',
  dynamicLayerOrchestrationMobileRuntimeOptimization:
    '@sta/dynamic_layer_orchestration_mobile_runtime_optimization_v1',
  autonomousMarketRegimeDetection: '@sta/autonomous_market_regime_detection_v1',
  cognitiveArbitrationConsensus: '@sta/cognitive_arbitration_consensus_v1',
  metaReliabilityLongitudinalTrust: '@sta/meta_reliability_longitudinal_trust_v1',
  selfEvolvingArchitectureReflectiveRefactor:
    '@sta/self_evolving_architecture_reflective_refactor_v1',
  epistemicIntegrityTruthCalibration: '@sta/epistemic_integrity_truth_calibration_v1',
  strategicMemoryGraphTemporalCausality:
    '@sta/strategic_memory_graph_temporal_causality_v1',
  cognitiveResourceEconomyAttentionAllocation:
    '@sta/cognitive_resource_economy_attention_allocation_v1',
  unifiedCognitiveStateExecutiveAwareness:
    '@sta/unified_cognitive_state_executive_awareness_v1',
  humanIntentContinuityAlignmentPreservation:
    '@sta/human_intent_continuity_alignment_preservation_v1',
  adaptiveExplorationAntiDogma: '@sta/adaptive_exploration_anti_dogma_v1',
  constitutionalGovernanceSystemCoherence: '@sta/constitutional_governance_system_coherence_v1',
  explainableGovernanceTransparentReasoning: '@sta/explainable_governance_transparent_reasoning_v1',
  runtimeSurvivalMobileResilience: '@sta/runtime_survival_mobile_resilience_v1',
  runtimeTelemetry: '@sta/runtime_telemetry_v1',
  forwardValidation: '@sta/forward_validation_v1',
  recommendationAuditLog: '@sta/recommendation_audit_log_v1',
  committeeNarrativeCache: '@sta/committee_narrative_cache_v1',
  committeeRedTeamCache: '@sta/committee_red_team_cache_v1',
  trustPlanPreview: '@sta/trust_plan_preview_v1',
  trustMonthlyReport: '@sta/trust_monthly_report_v1',
  trustOperatingPerformance: '@sta/trust_operating_performance_v1',
  bursaDisclosureCache: '@sta/bursa_disclosure_cache_v1',
  bursaMonitoringSnapshot: '@sta/bursa_monitoring_snapshot_v1',
  bursaWatchlist: '@sta/bursa_watchlist_v1',
  bursaAlertHistory: '@sta/bursa_alert_history_v1',
  bursaConciergeNotifications: '@sta/bursa_concierge_notifications_v1',
  bursaConciergeSound: '@sta/bursa_concierge_sound_v1',
  twelveHourTestMonitor: '@sta/twelve_hour_test_monitor_v1',
} as const;
